<?php if (isset($component)) { $__componentOriginal166a02a7c5ef5a9331faf66fa665c256 = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal166a02a7c5ef5a9331faf66fa665c256 = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'filament-panels::components.page.index','data' => []] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('filament-panels::page'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\Illuminate\View\AnonymousComponent::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes([]); ?>
<?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::processComponentKey($component); ?>

    <style>
        .pb-shell{display:flex;flex-direction:column;gap:1.25rem}.pb-hero{border-radius:1.5rem;padding:1.5rem;background:linear-gradient(135deg,rgba(15,23,42,.96),rgba(30,41,59,.9));color:#fff;box-shadow:0 18px 45px rgba(15,23,42,.18)}.pb-hero h2{font-size:1.55rem;font-weight:800;margin:0}.pb-hero p{margin:.4rem 0 0;color:rgba(255,255,255,.78);max-width:64rem}.pb-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.75rem}.pb-two{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.pb-three{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem}.pb-card,.pb-panel{border:1px solid rgba(148,163,184,.24);background:rgba(255,255,255,.9);border-radius:1.25rem;padding:1rem;box-shadow:0 12px 30px rgba(15,23,42,.06)}.dark .pb-card,.dark .pb-panel{background:rgba(15,23,42,.78);border-color:rgba(148,163,184,.18)}.pb-muted,.pb-card small{font-size:.78rem;color:rgb(100,116,139)}.dark .pb-muted,.dark .pb-card small{color:rgb(148,163,184)}.pb-kpi strong{display:block;font-size:1.35rem;margin-top:.2rem}.pb-card h3,.pb-row h4{font-weight:800;margin:0}.pb-pill{display:inline-flex;border-radius:999px;padding:.25rem .55rem;font-size:.72rem;font-weight:700;background:rgba(59,130,246,.12);color:rgb(37,99,235)}.pb-pill.success{background:rgba(34,197,94,.14);color:rgb(22,101,52)}.pb-pill.warning{background:rgba(245,158,11,.14);color:rgb(180,83,9)}.pb-pill.danger{background:rgba(239,68,68,.14);color:rgb(185,28,28)}.pb-pill.muted{background:rgba(100,116,139,.12);color:rgb(71,85,105)}.pb-toolbar{display:flex;justify-content:space-between;gap:.75rem;align-items:center}.pb-toolbar input,.pb-toolbar select{border:1px solid rgba(148,163,184,.35);border-radius:.85rem;padding:.55rem .7rem;background:white;min-width:12rem}.dark .pb-toolbar input,.dark .pb-toolbar select{background:rgba(15,23,42,.95)}.pb-row{display:grid;grid-template-columns:minmax(0,1.2fr) auto auto;gap:.75rem;align-items:center;border-top:1px solid rgba(148,163,184,.18);padding-top:.75rem;margin-top:.75rem}.pb-empty{text-align:center;border:1px dashed rgba(148,163,184,.45);border-radius:1rem;padding:1.5rem;color:rgb(100,116,139)}@media(max-width:1100px){.pb-grid,.pb-three,.pb-two{grid-template-columns:1fr 1fr}.pb-row{grid-template-columns:1fr}}@media(max-width:720px){.pb-grid,.pb-three,.pb-two{grid-template-columns:1fr}.pb-toolbar{align-items:stretch;flex-direction:column}.pb-toolbar input,.pb-toolbar select{width:100%}}
    </style>

    <div class="pb-shell">
        <section class="pb-hero">
            <h2>Assinatura</h2>
            <p>Área restrita para acompanhar plano, limites e cobranças da conta. Use apenas quando precisar revisar assinatura ou situação financeira da plataforma.</p>
        </section>

        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if (! ($temBilling)): ?>
            <section class="pb-panel"><strong>Cobrança não instalada neste banco.</strong><p class="pb-muted">As tabelas <code>assinaturas</code> e <code>pagamentos</code> não foram encontradas. A tela segue exibindo apenas planos e limites internos.</p></section>
        <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>

        <section class="pb-grid">
            <article class="pb-card pb-kpi"><small>Empresas</small><strong><?php echo e(number_format($resumo['empresas'] ?? 0, 0, ',', '.')); ?></strong></article>
            <article class="pb-card pb-kpi"><small>MRR previsto</small><strong><?php echo e('R$ ' . number_format($resumo['mrr_previsto'] ?? 0, 2, ',', '.')); ?></strong></article>
            <article class="pb-card pb-kpi"><small>Pagamentos abertos</small><strong><?php echo e(number_format($resumo['pagamentos_abertos'] ?? 0, 0, ',', '.')); ?></strong></article>
            <article class="pb-card pb-kpi"><small>Valor vencido</small><strong><?php echo e('R$ ' . number_format($resumo['valor_vencido'] ?? 0, 2, ',', '.')); ?></strong></article>
            <article class="pb-card pb-kpi"><small>Assinaturas ativas</small><strong><?php echo e(number_format($resumo['assinaturas_ativas'] ?? 0, 0, ',', '.')); ?></strong></article>
            <article class="pb-card pb-kpi"><small>Pagamentos vencidos</small><strong><?php echo e(number_format($resumo['pagamentos_vencidos'] ?? 0, 0, ',', '.')); ?></strong></article>
            <article class="pb-card pb-kpi"><small>Bloqueios ativos</small><strong><?php echo e(number_format($resumo['bloqueios_ativos'] ?? 0, 0, ',', '.')); ?></strong></article>
            <article class="pb-card pb-kpi"><small>Regras ativas</small><strong><?php echo e(number_format($resumo['regras_ativas'] ?? 0, 0, ',', '.')); ?></strong></article>
        </section>

        <section class="pb-panel pb-toolbar">
            <div><h3 style="font-weight:800;margin:0">Filtros</h3><p class="pb-muted" style="margin:.25rem 0 0">Busca e filtro compartilhados entre empresas, assinaturas e pagamentos.</p></div>
            <div style="display:flex;gap:.5rem;flex-wrap:wrap">
                <input type="search" wire:model.live.debounce.400ms="search" placeholder="Buscar empresa, gateway ou cobrança">
                <select wire:model.live="planFilter"><option value="todos">Todos os planos</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $planOptions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $codigo => $nome): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($codigo); ?>"><?php echo e($nome); ?></option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select>
                <button type="button" class="pb-pill" wire:click="clearFilters">Limpar</button>
            </div>
        </section>

        <section class="pb-three">
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $planos; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $plano): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
                <article class="pb-card">
                    <small><?php echo e($plano['codigo']); ?></small><h3><?php echo e($plano['nome']); ?></h3><p><strong><?php echo e($plano['preco']); ?></strong></p>
                    <p class="pb-muted">Usuários: <?php echo e(number_format($plano['usuarios'], 0, ',', '.')); ?> · Itens: <?php echo e(number_format($plano['itens'], 0, ',', '.')); ?> · Armazenamento: <?php echo e($plano['armazenamento']); ?> · IA: <?php echo e(number_format($plano['ia'], 0, ',', '.')); ?></p>
                    <div style="display:flex;gap:.35rem;flex-wrap:wrap"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $plano['features']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $feature): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><span class="pb-pill"><?php echo e(str_replace('_', ' ', $feature)); ?></span><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></div>
                </article>
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
        </section>

        <section class="pb-panel">
            <h3>Empresas e plano atual</h3>
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $empresas; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $empresa): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
                <div class="pb-row"><div><h4><?php echo e($empresa['nome']); ?></h4><small><?php echo e($empresa['email'] ?: 'Sem e-mail'); ?> · Usuários <?php echo e($empresa['usuarios']); ?> · Itens <?php echo e($empresa['itens']); ?> · Armazenamento <?php echo e($empresa['armazenamento']); ?></small></div><strong><?php echo e($empresa['plano']); ?></strong><span class="pb-pill <?php echo e($empresa['status_tone']); ?>"><?php echo e($empresa['status']); ?></span></div>
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
                <div class="pb-empty">Nenhuma empresa encontrada.</div>
            <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
        </section>

        <section class="pb-two">
            <article class="pb-card"><h3>Assinaturas administrativas</h3><p class="pb-muted">Plano/contrato principal por empresa.</p><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $assinaturas; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $assinatura): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><div class="pb-row"><div><h4><?php echo e($assinatura['empresa']); ?></h4><small><?php echo e($assinatura['plano']); ?> · <?php echo e($assinatura['ciclo']); ?> · <?php echo e($assinatura['gateway']); ?></small></div><div><strong><?php echo e($assinatura['valor']); ?></strong><br><small>Vence <?php echo e($assinatura['vencimento']); ?></small></div><span class="pb-pill <?php echo e($assinatura['tone']); ?>"><?php echo e($assinatura['status']); ?></span></div><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?><div class="pb-empty">Nenhuma assinatura encontrada.</div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></article>
            <article class="pb-card"><h3>Pagamentos recentes</h3><p class="pb-muted">Cobranças abertas, vencidas ou pagas.</p><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $pagamentos; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $pagamento): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><div class="pb-row"><div><h4><?php echo e($pagamento['empresa']); ?></h4><small><?php echo e($pagamento['plano']); ?> · <?php echo e($pagamento['tipo']); ?> · venc. <?php echo e($pagamento['vencimento']); ?></small></div><div><strong><?php echo e($pagamento['valor']); ?></strong><br><small>Pago <?php echo e($pagamento['pago_em']); ?></small></div><span class="pb-pill <?php echo e($pagamento['tone']); ?>"><?php echo e($pagamento['status']); ?></span></div><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?><div class="pb-empty">Nenhum pagamento encontrado.</div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></article>
        </section>

        <section class="pb-two">
            <article class="pb-card"><h3>Bloqueios de cobrança</h3><p class="pb-muted">Empresas bloqueadas por cobrança ou regra comercial.</p><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $bloqueios; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $bloqueio): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><div class="pb-row"><div><h4><?php echo e($bloqueio['empresa']); ?></h4><small><?php echo e($bloqueio['reason']); ?></small></div><strong><?php echo e($bloqueio['locked_at']); ?></strong><span class="pb-pill danger">bloqueado</span></div><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?><div class="pb-empty">Nenhum bloqueio ativo.</div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></article>
            <article class="pb-card"><h3>Regras de cobrança</h3><p class="pb-muted">Régua de ação após vencimento.</p><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $regras; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $regra): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><div class="pb-row"><div><h4><?php echo e($regra['name']); ?></h4><small><?php echo e($regra['message'] ?: 'Sem mensagem personalizada'); ?></small></div><strong><?php echo e($regra['days']); ?> dia(s)</strong><span class="pb-pill <?php echo e($regra['active'] ? 'success' : 'muted'); ?>"><?php echo e($regra['action']); ?></span></div><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?><div class="pb-empty">Nenhuma regra cadastrada.</div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></article>
        </section>
    </div>
 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal166a02a7c5ef5a9331faf66fa665c256)): ?>
<?php $attributes = $__attributesOriginal166a02a7c5ef5a9331faf66fa665c256; ?>
<?php unset($__attributesOriginal166a02a7c5ef5a9331faf66fa665c256); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal166a02a7c5ef5a9331faf66fa665c256)): ?>
<?php $component = $__componentOriginal166a02a7c5ef5a9331faf66fa665c256; ?>
<?php unset($__componentOriginal166a02a7c5ef5a9331faf66fa665c256); ?>
<?php endif; ?>
<?php /**PATH C:\xampp\htdocs\prazzu\resources\views/filament/pages/planos-billing.blade.php ENDPATH**/ ?>