<?php
    $empresa = $detail['empresa'] ?? [];
    $storage = $detail['armazenamento'] ?? [];
    $tarefas = $detail['tarefas'] ?? [];
    $atendimentos = $detail['atendimentos'] ?? [];
    $portal = $detail['portal'] ?? [];
    $financeiro = $detail['financeiro'] ?? [];
    $contratos = $detail['contratos'] ?? [];
    $validade = $detail['validade'] ?? [];
    $governanca = $detail['governanca'] ?? [];
    $acoes = collect($detail['acoes'] ?? [])->filter(fn ($action) => filled($action['url'] ?? null));
    $recomendacoes = $detail['recomendacoes'] ?? [];
    $pesados = $storage['pesados'] ?? [];
?>
<div class="storage-client-modal">
    <section class="storage-client-hero">
        <article class="storage-client-card">
            <h3><?php echo e($empresa['nome'] ?? 'Cliente'); ?></h3>
            <p><?php echo e($empresa['razao_social'] ?? 'Razão social não informada'); ?> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(! empty($empresa['cnpj'])): ?> · CNPJ <?php echo e($empresa['cnpj']); ?> <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></p>
            <p>Status: <strong><?php echo e(ucfirst((string) ($empresa['status'] ?? 'não informado'))); ?></strong> · Plano: <strong><?php echo e($empresa['plano'] ?? 'sem plano'); ?></strong> · Desde: <strong><?php echo e($empresa['desde'] ?? 'Não informado'); ?></strong></p>
            <p>Responsável: <strong><?php echo e($empresa['responsavel'] ?: 'Não informado'); ?></strong> · Portal: <strong><?php echo e(($empresa['portal_ativo'] ?? false) ? 'Ativo' : 'Inativo'); ?></strong></p>
        </article>
        <article class="storage-client-card">
            <h3><?php echo e($storage['total_formatado'] ?? '0 B'); ?> usados</h3>
            <p>Limite: <?php echo e($storage['limite_formatado'] ?? '0 B'); ?> · <?php echo e($storage['percentual'] ?? 0); ?>% utilizado</p>
            <div class="storage-client-progress <?php echo e($storage['tom'] ?? 'success'); ?>"><span style="width: <?php echo e(min(100, (int) ($storage['percentual'] ?? 0))); ?>%"></span></div>
            <p>Espaço recuperável estimado: <strong><?php echo e($storage['recuperavel_formatado'] ?? '0 B'); ?></strong></p>
        </article>
    </section>

    <section class="storage-client-kpis">
        <article class="storage-client-kpi"><span>Arquivos</span><strong><?php echo e(number_format((int) ($storage['arquivos'] ?? 0), 0, ',', '.')); ?></strong></article>
        <article class="storage-client-kpi"><span>Expirados</span><strong><?php echo e(number_format((int) ($storage['expirados'] ?? 0), 0, ',', '.')); ?></strong></article>
        <article class="storage-client-kpi"><span>Tarefas abertas</span><strong><?php echo e(number_format((int) ($tarefas['abertas'] ?? 0), 0, ',', '.')); ?></strong></article>
        <article class="storage-client-kpi"><span>Atendimentos abertos</span><strong><?php echo e(number_format((int) ($atendimentos['abertos'] ?? 0), 0, ',', '.')); ?></strong></article>
    </section>

    <section class="storage-client-grid">
        <article class="storage-client-section"><h4>Documentos e armazenamento</h4><div class="storage-client-line"><span>Maior arquivo</span><strong><?php echo e($storage['maior_arquivo']['nome'] ?? 'Não identificado'); ?></strong></div><div class="storage-client-line"><span>Tamanho do maior</span><strong><?php echo e($storage['maior_arquivo']['tamanho_formatado'] ?? '0 B'); ?></strong></div><div class="storage-client-line"><span>Vencidos/antigos</span><strong><?php echo e(number_format((int) ($storage['expirados'] ?? 0), 0, ',', '.')); ?></strong></div><div class="storage-client-line"><span>Portal documentos</span><strong><?php echo e(number_format((int) ($portal['documentos'] ?? 0), 0, ',', '.')); ?></strong></div></article>
        <article class="storage-client-section"><h4>Tarefas, SLA e prazos</h4><div class="storage-client-line"><span>Abertas</span><strong><?php echo e(number_format((int) ($tarefas['abertas'] ?? 0), 0, ',', '.')); ?></strong></div><div class="storage-client-line"><span>Atrasadas</span><strong><?php echo e(number_format((int) ($tarefas['atrasadas'] ?? 0), 0, ',', '.')); ?></strong></div><div class="storage-client-line"><span>Críticas</span><strong><?php echo e(number_format((int) ($tarefas['criticas'] ?? 0), 0, ',', '.')); ?></strong></div><div class="storage-client-line"><span>SLA vencido</span><strong><?php echo e(number_format((int) ($tarefas['slaVencido'] ?? 0), 0, ',', '.')); ?></strong></div></article>
        <article class="storage-client-section"><h4>Atendimentos e portal</h4><div class="storage-client-line"><span>Atendimentos críticos</span><strong><?php echo e(number_format((int) ($atendimentos['criticos'] ?? 0), 0, ',', '.')); ?></strong></div><div class="storage-client-line"><span>Aguardando cliente</span><strong><?php echo e(number_format((int) ($atendimentos['aguardando_cliente'] ?? 0), 0, ',', '.')); ?></strong></div><div class="storage-client-line"><span>Solicitações portal</span><strong><?php echo e(number_format((int) ($portal['solicitacoes_abertas'] ?? 0), 0, ',', '.')); ?></strong></div><div class="storage-client-line"><span>Último contato</span><strong><?php echo e($atendimentos['ultimo_contato'] ?? $portal['ultima_mensagem'] ?? 'Não informado'); ?></strong></div></article>
        <article class="storage-client-section"><h4>Financeiro e cobranças</h4><div class="storage-client-line"><span>Cobranças abertas</span><strong><?php echo e(number_format((int) ($financeiro['abertas'] ?? 0), 0, ',', '.')); ?></strong></div><div class="storage-client-line"><span>Cobranças vencidas</span><strong><?php echo e(number_format((int) ($financeiro['vencidas'] ?? 0), 0, ',', '.')); ?></strong></div><div class="storage-client-line"><span>Valor vencido</span><strong><?php echo e($financeiro['vencido_formatado'] ?? 'R$ 0,00'); ?></strong></div><div class="storage-client-line"><span>Próximo vencimento</span><strong><?php echo e($financeiro['proximo_vencimento'] ?? 'Sem vencimento'); ?></strong></div></article>
        <article class="storage-client-section"><h4>Contratos, validades e governança</h4><div class="storage-client-line"><span>Contratos ativos</span><strong><?php echo e(number_format((int) ($contratos['ativos'] ?? 0), 0, ',', '.')); ?></strong></div><div class="storage-client-line"><span>Contratos vencendo</span><strong><?php echo e(number_format((int) ($contratos['vencendo'] ?? 0), 0, ',', '.')); ?></strong></div><div class="storage-client-line"><span>Validades vencidas</span><strong><?php echo e(number_format((int) ($validade['vencidos'] ?? 0), 0, ',', '.')); ?></strong></div><div class="storage-client-line"><span>Aprovações pendentes</span><strong><?php echo e(number_format((int) ($governanca['aprovacoes_pendentes'] ?? 0), 0, ',', '.')); ?></strong></div></article>
        <article class="storage-client-section"><h4>Recomendação operacional</h4><div class="storage-client-recos"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $recomendacoes; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $recomendacao): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><div class="storage-client-reco <?php echo e($recomendacao['tom'] ?? 'success'); ?>"><?php echo e($recomendacao['texto'] ?? ''); ?></div><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></div></article>
    </section>

    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(count($pesados) > 0): ?>
        <section class="storage-client-section"><h4>Arquivos que explicam o consumo</h4><div class="storage-client-files"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $pesados; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $arquivo): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><div class="storage-client-file"><strong title="<?php echo e($arquivo['nome'] ?? 'Arquivo'); ?>"><?php echo e($arquivo['nome'] ?? 'Arquivo'); ?></strong><span><?php echo e($arquivo['tamanho_formatado'] ?? '0 B'); ?> · <?php echo e($arquivo['origem'] ?? 'Origem'); ?></span></div><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></div></section>
    <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>

    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($acoes->isNotEmpty()): ?>
        <section class="storage-client-section"><h4>Continuar análise</h4><div class="storage-client-actions"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $acoes; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $acao): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><a href="<?php echo e($acao['url']); ?>" class="storage-client-action <?php echo e($acao['style'] ?? 'secondary'); ?>"><?php echo e($acao['label'] ?? 'Abrir'); ?></a><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></div></section>
    <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
</div>
<?php /**PATH C:\xampp\htdocs\prazzu\resources\views\filament\pages\partials\armazenamento-cliente-modal.blade.php ENDPATH**/ ?>