<?php

namespace App\Support;

class ProductProfileNavigation
{
    public static function profiles(): array
    {
        return [
            'completo' => [
                'label' => 'Perfil Completo',
                'hint' => 'Todos os módulos do sistema',
                'description' => 'Mostra a navegação completa para implantação, auditoria, configuração e operação avançada.',
                'visible_labels' => ['*'],
                'hidden_labels' => [],
                'aliases' => [],
                'priority' => 'Completo',
                'recommended_for' => 'Super admin, implantação, auditoria, manutenção e usuários avançados.',
            ],
            'escritorio_contabil' => [
                'label' => 'Escritório Contábil',
                'hint' => 'Fluxo contábil organizado',
                'description' => 'Menu reorganizado por responsabilidade única: visão geral, execução, pendências, clientes, documentos, contratos, financeiro, aprovações, calendário, relatórios, auditoria e administração.',
                'priority' => 'Foco contábil',
                'recommended_for' => 'Equipe operacional de escritório contábil, gestores de carteira, atendimento e responsáveis por obrigações/prazos.',
                'visible_labels' => [
                    'Visão Geral Contábil',
                    'Central Operacional',
                    'Pendências e Alertas',
                    'Clientes',
                    'Atendimentos',
                    'Documentos',
                    'Contratos',
                    'Financeiro',
                    'Aprovações',
                    'Calendário Operacional',
                    'Visualizações da Operação',
                    'Relatórios',
                    'Auditoria e Riscos',
                    'Administração',
                    'Configurações',
                    'Conta',
                ],
                'hidden_labels' => [
                    'Home',
                    'Central de Evolução',
                    'Dashboard Executivo',
                    'Dashboard Executivo Contábil',
                    'Dashboards',
                    'Painéis',
                    'Painéis Globais',
                    'Dashboard Configurável',
                    'Painel Configurável',
                    'Visualizar Dashboard',
                    'Dashboard - Tabelas',
                    'Painéis Operacionais',
                    'Centro Operacional',
                    'Operação Interna',
                    'Gestão da Operação',
                    'Tarefas',
                    'Tarefas Operacionais',
                    'Fluxos Operacionais',
                    'Checklist',
                    'SLA e Prazos',
                    'Pendências',
                    'Portal do Cliente',
                    'Armazenamento',
                    'Validades',
                    'Assinaturas',
                    'Cobranças',
                    'Calendário',
                    'Timeline Operacional',
                    'Timeline Global',
                    'Kanban',
                    'Kanban Operacional',
                    'Gantt Enterprise',
                    'Cronograma Gantt',
                    'Projetos',
                    'Relatórios Exportáveis',
                    'Relatórios Personalizados',
                    'Visualizar Relatórios',
                    'Riscos',
                    'Auditoria',
                    'Auditoria Administrativa',
                    'Auditoria completa',
                    'Auditoria Completa',
                    'Compliance Interno',
                    'Compliance Engine',
                    'Central de Aprovações',
                    'Central Administrativa',
                    'Usuários',
                    'Perfis e Permissões',
                    'Permissões',
                    'Empresa',
                    'Empresas',
                    'Equipes',
                    'Gestão de Planos',
                    'Assinatura',
                    'Onboarding',
                    'White Label',
                    'Gestão Documental Enterprise',
                    'Templates Enterprise',
                    'Modelos Enterprise',
                    'Automações úteis',
                    'Inteligência do Produto',
                    'Saúde do Sistema',
                    'Categorias',
                    'Tags',
                    'Assistente Operacional',
                    'Navegação Contextual',
                ],
                'aliases' => [
                    'Dashboard' => 'Visão Geral Contábil',
                    'Dashboard Executivo' => 'Visão Geral Contábil',
                    'Dashboard Executivo Contábil' => 'Visão Geral Contábil',
                    'Dashboards' => 'Visão Geral Contábil',
                    'Painéis' => 'Visão Geral Contábil',
                    'Painéis Globais' => 'Visão Geral Contábil',
                    'Dashboard Configurável' => 'Visão Geral Contábil',
                    'Painel Configurável' => 'Visão Geral Contábil',
                    'Centro Operacional' => 'Central Operacional',
                    'Operação Interna' => 'Central Operacional',
                    'Gestão da Operação' => 'Central Operacional',
                    'Tarefas' => 'Central Operacional',
                    'Tarefas Operacionais' => 'Central Operacional',
                    'Fluxos Operacionais' => 'Central Operacional',
                    'Checklist' => 'Central Operacional',
                    'Pendências' => 'Pendências e Alertas',
                    'SLA' => 'Calendário Operacional',
                    'SLA e Prazos' => 'Calendário Operacional',
                    'Monitor de SLA e Prazos' => 'Calendário Operacional',
                    'Prazos' => 'Calendário Operacional',
                    'Calendário' => 'Calendário Operacional',
                    'Portal do Cliente' => 'Atendimentos',
                    'Armazenamento' => 'Documentos',
                    'Validades' => 'Documentos',
                    'Assinaturas' => 'Contratos',
                    'Cobranças' => 'Financeiro',
                    'Contas a Receber' => 'Financeiro',
                    'Central de Aprovações' => 'Aprovações',
                    'Timeline Operacional' => 'Visualizações da Operação',
                    'Timeline' => 'Visualizações da Operação',
                    'Kanban' => 'Visualizações da Operação',
                    'Kanban Operacional' => 'Visualizações da Operação',
                    'Gantt Enterprise' => 'Visualizações da Operação',
                    'Cronograma Gantt' => 'Visualizações da Operação',
                    'Relatórios Exportáveis' => 'Relatórios',
                    'Relatórios Personalizados' => 'Relatórios',
                    'Riscos' => 'Auditoria e Riscos',
                    'Auditoria' => 'Auditoria e Riscos',
                    'Auditoria Administrativa' => 'Auditoria e Riscos',
                    'Auditoria completa' => 'Auditoria e Riscos',
                    'Auditoria Completa' => 'Auditoria e Riscos',
                    'Compliance Interno' => 'Auditoria e Riscos',
                    'Configurações e Administração' => 'Administração',
                    'Central Administrativa' => 'Administração',
                    'Usuários' => 'Administração',
                    'Perfis e Permissões' => 'Administração',
                    'Permissões' => 'Administração',
                    'Empresa' => 'Administração',
                    'Empresas' => 'Administração',
                    'Equipes' => 'Administração',
                    'Gestão de Planos' => 'Conta',
                    'Assinatura' => 'Conta',
                    'Onboarding' => 'Conta',
                    'White Label' => 'Conta',
                    'Automações úteis' => 'Configurações',
                    'Configurações técnicas' => 'Configurações',
                ],
            ],
            'juridico' => [
                'label' => 'Jurídico',
                'hint' => 'Contratos, documentos e aprovações',
                'description' => 'Foco em documentos, contratos, prazos, aprovações, auditoria e atendimento ao cliente.',
                'priority' => 'Foco jurídico',
                'recommended_for' => 'Equipes jurídicas que trabalham com contratos, documentos, prazos, aprovações e histórico auditável.',
                'visible_labels' => [
                    'Home',
                    'Centro Operacional',
                    'Pendências',
                    'Clientes',
                    'Atendimentos',
                    'Documentos',
                    'Contratos',
                    'Gestão Documental Enterprise',
                    'Central de Aprovações',
                    'Relatórios',
                    'Dashboards',
                    'Dashboard Executivo',
                    'Calendário',
                    'Configurações',
                    'Usuários',
                    'Empresas',
                    'Permissões',
                ],
                'hidden_labels' => [
                    'Inteligência do Produto',
                    'Saúde do Sistema',
                    'White Label',
                    'Central de Evolução',
                    'Dashboard - Tabelas',
                    'Projetos',
                ],
                'aliases' => [
                    'Portal Cliente' => 'Portal do Cliente',
                    'Aprovações' => 'Central de Aprovações',
                ],
            ],
            'rh' => [
                'label' => 'RH',
                'hint' => 'Pessoas, tarefas, contratos e documentos',
                'description' => 'Foco em rotinas de pessoas, documentos, contratos, prazos e acompanhamento operacional.',
                'priority' => 'Foco RH',
                'recommended_for' => 'Rotinas internas de RH, admissões, documentos, prazos, tarefas e acompanhamento operacional.',
                'visible_labels' => [
                    'Home',
                    'Centro Operacional',
                    'Pendências',
                    'Clientes',
                    'Atendimentos',
                    'Documentos',
                    'Contratos',
                    'Calendário',
                    'Relatórios',
                    'Dashboards',
                    'Dashboard Executivo',
                    'Central de Aprovações',
                    'Configurações',
                    'Usuários',
                    'Empresas',
                    'Permissões',
                ],
                'hidden_labels' => [
                    'Inteligência do Produto',
                    'Saúde do Sistema',
                    'White Label',
                    'Central de Evolução',
                    'Dashboard - Tabelas',
                    'Projetos',
                    'Compliance Engine',
                    'Compliance Interno',
                ],
                'aliases' => [
                    'Aprovações' => 'Central de Aprovações',
                ],
            ],
            'operacional' => [
                'label' => 'Operacional',
                'hint' => 'Execução diária simples',
                'description' => 'Menu reduzido para quem só precisa executar tarefas, acompanhar prazos e resolver pendências.',
                'priority' => 'Foco execução',
                'recommended_for' => 'Usuários que executam a rotina diária e não precisam ver módulos administrativos ou estratégicos.',
                'visible_labels' => [
                    'Home',
                    'Centro Operacional',
                    'Pendências',
                    'Clientes',
                    'Atendimentos',
                    'Documentos',
                    'Financeiro',
                    'Calendário',
                    'Relatórios',
                    'Dashboard Executivo',
                    'Central de Aprovações',
                ],
                'hidden_labels' => [
                    'Configurações',
                    'Usuários',
                    'Empresas',
                    'Permissões',
                    'Onboarding',
                    'Inteligência do Produto',
                    'Saúde do Sistema',
                    'White Label',
                    'Central de Evolução',
                    'Dashboard - Tabelas',
                    'Projetos',
                    'Compliance Engine',
                    'Compliance Interno',
                    'Gestão Documental Enterprise',
                    'Templates Enterprise',
                    'Modelos Enterprise',
                    'Assistente Operacional',
                    'Navegação Contextual',
                    'Timeline Global',
                ],
                'aliases' => [
                    'Aprovações' => 'Central de Aprovações',
                ],
            ],
        ];
    }

    public static function defaultProfile(): string
    {
        return 'completo';
    }

    public static function availableProfileKeys(): array
    {
        return array_keys(self::profiles());
    }

    public static function browserPayload(): array
    {
        return collect(self::profiles())
            ->map(fn (array $profile): array => [
                'label' => $profile['label'],
                'hint' => $profile['hint'],
                'description' => $profile['description'] ?? $profile['hint'],
                'priority' => $profile['priority'] ?? $profile['label'],
                'recommendedFor' => $profile['recommended_for'] ?? null,
                'visibleLabels' => $profile['visible_labels'],
                'hiddenLabels' => $profile['hidden_labels'] ?? [],
                'aliases' => array_merge(self::globalAliases(), $profile['aliases'] ?? []),
                'visibleCount' => in_array('*', $profile['visible_labels'], true) ? null : count($profile['visible_labels']),
                'hiddenCount' => count($profile['hidden_labels'] ?? []),
            ])
            ->all();
    }

    private static function globalAliases(): array
    {
        return [
            'Relatar Bug / Melhoria' => 'Central de Evolução',
            'Dashboard' => 'Visão Geral Contábil',
            'Dashboard Executivo' => 'Visão Geral Contábil',
            'Dashboard Executivo Contábil' => 'Visão Geral Contábil',
            'Dashboards' => 'Visão Geral Contábil',
            'Painéis' => 'Visão Geral Contábil',
            'Dashboard Configurável' => 'Visão Geral Contábil',
            'Centro Operacional' => 'Central Operacional',
            'Operação Interna' => 'Central Operacional',
            'Gestão da Operação' => 'Central Operacional',
            'Tarefas' => 'Central Operacional',
            'Tarefas Operacionais' => 'Central Operacional',
            'Fluxos Operacionais' => 'Central Operacional',
            'Pendências' => 'Pendências e Alertas',
            'SLA' => 'Calendário Operacional',
            'SLA e Prazos' => 'Calendário Operacional',
            'Calendário' => 'Calendário Operacional',
            'Portal Cliente' => 'Atendimentos',
            'Portal do Cliente' => 'Atendimentos',
            'Armazenamento' => 'Documentos',
            'Validades' => 'Documentos',
            'Assinaturas' => 'Contratos',
            'Cobranças' => 'Financeiro',
            'Central de Aprovações' => 'Aprovações',
            'Timeline Operacional' => 'Visualizações da Operação',
            'Timeline' => 'Visualizações da Operação',
            'Kanban' => 'Visualizações da Operação',
            'Gantt Enterprise' => 'Visualizações da Operação',
            'Cronograma Gantt' => 'Visualizações da Operação',
            'Relatórios Exportáveis' => 'Relatórios',
            'Relatórios Personalizados' => 'Relatórios',
            'Riscos' => 'Auditoria e Riscos',
            'Auditoria' => 'Auditoria e Riscos',
            'Auditoria Administrativa' => 'Auditoria e Riscos',
            'Auditoria completa' => 'Auditoria e Riscos',
            'Auditoria Completa' => 'Auditoria e Riscos',
            'Compliance Interno' => 'Auditoria e Riscos',
            'Configurações e Administração' => 'Administração',
            'Central Administrativa' => 'Administração',
            'Usuários' => 'Administração',
            'Perfis e Permissões' => 'Administração',
            'Permissões' => 'Administração',
            'Empresa' => 'Administração',
            'Empresas' => 'Administração',
            'Equipes' => 'Administração',
            'Gestão de Planos' => 'Conta',
            'Assinatura' => 'Conta',
            'Onboarding' => 'Conta',
            'White Label' => 'Conta',
            'Automações úteis' => 'Configurações',
            'Configurações técnicas' => 'Configurações',
        ];
    }
}
