<?php

namespace App\Support;

class ProductProfileNavigation
{
    public static function profiles(): array
    {
        return [
            'completo' => [
                'label' => 'Perfil Completo',
                'hint' => 'Todos os módulos do sistema',
                'description' => 'Mostra a navegação completa para implantação, auditoria, configuração e operação avançada.',
                'visible_labels' => ['*'],
                'hidden_labels' => [],
                'aliases' => [],
                'priority' => 'Completo',
                'recommended_for' => 'Super admin, implantação, auditoria, manutenção e usuários avançados.',
            ],
            'escritorio_contabil' => [
                'label' => 'Escritório Contábil',
                'hint' => 'Prazos, clientes, documentos e risco',
                'description' => 'Menu enxuto para rotina contábil: executar tarefas, controlar prazos, cobrar documentos, acompanhar clientes e evitar multas.',
                'priority' => 'Foco contábil',
                'recommended_for' => 'Equipe operacional de escritório contábil, gestores de carteira, atendimento e responsáveis por obrigações/prazos.',
                'visible_labels' => [
                    'Home',
                    'Centro Operacional',
                    'Tarefas',
                    'Fluxos Operacionais',
                    'SLA e Prazos',
                    'Checklist',
                    'Pendências',
                    'Clientes',
                    'Portal do Cliente',
                    'Atendimentos',
                    'Documentos',
                    'Contratos',
                    'Validades',
                    'Cobranças',
                    'Financeiro',
                    'Relatórios',
                    'Dashboards',
                    'Dashboard Executivo',
                    'Relatórios Exportáveis',
                    'Riscos',
                    'Calendário',
                    'Timeline Operacional',
                    'Central de Aprovações',
                    'Auditoria',
                    'Configurações',
                    'Usuários',
                    'Empresas',
                    'Permissões',
                    'Onboarding',
                    'Automações úteis',
                ],
                'hidden_labels' => [
                    'Assinaturas',
                    'Assistente Operacional',
                    'Compliance Engine',
                    'Interno',
                    'Dashboard Configurável',
                    'Visualizar Dashboard',
                    'Gantt Enterprise',
                    'Gestão Documental Enterprise',
                    'Inteligência do Produto',
                    'Kanban',
                    'Navegação Contextual',
                    'Projetos',
                    'Saúde do Sistema',
                    'Templates Enterprise',
                    'Timeline Global',
                    'White Label',
                    'Categorias',
                    'Tags',
                    'Modelos Enterprise',
                    'Relatar Bug / Melhoria',
                    'Dashboard - Tabelas',
                    'Visualizar Relatórios',
                ],
                'aliases' => [
                    'SLA' => 'SLA e Prazos',
                    'Prazos' => 'SLA e Prazos',
                    'Portal Cliente' => 'Portal do Cliente',
                    'Dashboard' => 'Dashboards',
                    'Aprovações' => 'Central de Aprovações',
                    'Automação' => 'Automações úteis',
                    'Automações' => 'Automações úteis',
                ],
            ],
            'juridico' => [
                'label' => 'Jurídico',
                'hint' => 'Contratos, documentos e aprovações',
                'description' => 'Foco em documentos, contratos, prazos, aprovações, auditoria e atendimento ao cliente.',
                'priority' => 'Foco jurídico',
                'recommended_for' => 'Equipes jurídicas que trabalham com contratos, documentos, prazos, aprovações e histórico auditável.',
                'visible_labels' => [
                    'Home',
                    'Centro Operacional',
                    'Tarefas',
                    'Fluxos Operacionais',
                    'SLA e Prazos',
                    'Checklist',
                    'Pendências',
                    'Clientes',
                    'Portal do Cliente',
                    'Atendimentos',
                    'Documentos',
                    'Contratos',
                    'Validades',
                    'Gestão Documental Enterprise',
                    'Central de Aprovações',
                    'Auditoria',
                    'Relatórios',
                    'Dashboards',
                    'Dashboard Executivo',
                    'Riscos',
                    'Calendário',
                    'Timeline Operacional',
                    'Configurações',
                    'Usuários',
                    'Empresas',
                    'Permissões',
                ],
                'hidden_labels' => [
                    'Inteligência do Produto',
                    'Saúde do Sistema',
                    'White Label',
                    'Relatar Bug / Melhoria',
                    'Dashboard - Tabelas',
                    'Gantt Enterprise',
                    'Kanban',
                    'Projetos',
                ],
                'aliases' => [
                    'Portal Cliente' => 'Portal do Cliente',
                    'Aprovações' => 'Central de Aprovações',
                ],
            ],
            'rh' => [
                'label' => 'RH',
                'hint' => 'Pessoas, tarefas, contratos e documentos',
                'description' => 'Foco em rotinas de pessoas, documentos, contratos, prazos e acompanhamento operacional.',
                'priority' => 'Foco RH',
                'recommended_for' => 'Rotinas internas de RH, admissões, documentos, prazos, tarefas e acompanhamento operacional.',
                'visible_labels' => [
                    'Home',
                    'Centro Operacional',
                    'Tarefas',
                    'Fluxos Operacionais',
                    'SLA e Prazos',
                    'Checklist',
                    'Pendências',
                    'Clientes',
                    'Atendimentos',
                    'Documentos',
                    'Contratos',
                    'Validades',
                    'Calendário',
                    'Timeline Operacional',
                    'Relatórios',
                    'Dashboards',
                    'Dashboard Executivo',
                    'Central de Aprovações',
                    'Auditoria',
                    'Configurações',
                    'Usuários',
                    'Empresas',
                    'Permissões',
                ],
                'hidden_labels' => [
                    'Inteligência do Produto',
                    'Saúde do Sistema',
                    'White Label',
                    'Relatar Bug / Melhoria',
                    'Dashboard - Tabelas',
                    'Gantt Enterprise',
                    'Kanban',
                    'Projetos',
                    'Compliance Engine',
                    'Compliance Interno',
                ],
                'aliases' => [
                    'Aprovações' => 'Central de Aprovações',
                ],
            ],
            'operacional' => [
                'label' => 'Operacional',
                'hint' => 'Execução diária simples',
                'description' => 'Menu reduzido para quem só precisa executar tarefas, acompanhar prazos e resolver pendências.',
                'priority' => 'Foco execução',
                'recommended_for' => 'Usuários que executam a rotina diária e não precisam ver módulos administrativos ou estratégicos.',
                'visible_labels' => [
                    'Home',
                    'Centro Operacional',
                    'Tarefas',
                    'Fluxos Operacionais',
                    'SLA e Prazos',
                    'Checklist',
                    'Pendências',
                    'Clientes',
                    'Atendimentos',
                    'Documentos',
                    'Cobranças',
                    'Financeiro',
                    'Calendário',
                    'Timeline Operacional',
                    'Relatórios',
                    'Dashboard Executivo',
                    'Riscos',
                    'Central de Aprovações',
                ],
                'hidden_labels' => [
                    'Configurações',
                    'Usuários',
                    'Empresas',
                    'Permissões',
                    'Onboarding',
                    'Inteligência do Produto',
                    'Saúde do Sistema',
                    'White Label',
                    'Relatar Bug / Melhoria',
                    'Dashboard - Tabelas',
                    'Gantt Enterprise',
                    'Kanban',
                    'Projetos',
                    'Compliance Engine',
                    'Compliance Interno',
                    'Gestão Documental Enterprise',
                    'Templates Enterprise',
                    'Modelos Enterprise',
                    'Assistente Operacional',
                    'Navegação Contextual',
                    'Timeline Global',
                ],
                'aliases' => [
                    'Aprovações' => 'Central de Aprovações',
                ],
            ],
        ];
    }

    public static function defaultProfile(): string
    {
        return 'completo';
    }

    public static function availableProfileKeys(): array
    {
        return array_keys(self::profiles());
    }

    public static function browserPayload(): array
    {
        return collect(self::profiles())
            ->map(fn (array $profile): array => [
                'label' => $profile['label'],
                'hint' => $profile['hint'],
                'description' => $profile['description'] ?? $profile['hint'],
                'priority' => $profile['priority'] ?? $profile['label'],
                'recommendedFor' => $profile['recommended_for'] ?? null,
                'visibleLabels' => $profile['visible_labels'],
                'hiddenLabels' => $profile['hidden_labels'] ?? [],
                'aliases' => $profile['aliases'] ?? [],
                'visibleCount' => in_array('*', $profile['visible_labels'], true) ? null : count($profile['visible_labels']),
                'hiddenCount' => count($profile['hidden_labels'] ?? []),
            ])
            ->all();
    }
}
